"""`bootstrap(planet, program)` — create a project directory ready for the pipeline.

What it does
------------
1. Queries NASA Exoplanet Archive for system parameters → writes `target.json`.
2. Creates the standard project directory layout.
3. Writes a minimal `config.yaml` stub with only pipeline overrides (knobs that the
   NASA Exoplanet Archive doesn't provide).

What it does NOT do
-------------------
- Download data (call `tswift.fetch(project_dir, program_id)` for that — keeps bootstrap
  fast and offline-safe).
- Guess the instrument mode (this requires knowing which observation, which the user
  chooses when fetching). Mode is set in config.yaml after fetch.
"""
from __future__ import annotations

import logging
import os
import textwrap
from pathlib import Path
from typing import Optional

from tswift.contracts import Target
from tswift.target_db import query_target

logger = logging.getLogger(__name__)


_PROJECT_SUBDIRS = [
    "data/uncal",
    "data/stage1",
    "data/stage2",
    "data/group_bg",
    "data/ramp",
    "product",
    "logs",
]


_CONFIG_TEMPLATE = """\
# Pipeline overrides for {planet_name}. Auto-generated by `tswift bootstrap`.
#
# SYSTEM PARAMS (Teff, period, Rp/Rs, ...) live in `target.json` and are auto-populated
# from the NASA Exoplanet Archive. Override them there if you have a better reference.
#
# Everything below is pipeline-level knobs: extraction window, MCMC priors widths,
# combine options. Agent or human edits happen here, not in target.json.

instrument:
  mode: null          # "SOSS" | "G395H" | "PRISM" | "MIRI_LRS" — set after `tswift fetch` confirms the obs

paths:
  crds_cache: "{crds_cache}"   # CRDS reference-file cache (first run downloads several GB)
  ld_data: "{ld_data}"         # exotic_ld stellar-grid data dir — REQUIRED for spectral fits

extraction:
  bad_pixel:
    n_sigma: 5.0
    min_sigma: 2.0
    replace_with_nan: true
  trace_half_width: 22     # start generous; aperture optimizer narrows via OOT scatter
  aperture_criterion: "per_channel"   # "per_channel" | "wl_rms"
  outlier_window: 20
  outlier_threshold: 4.0

mcmc:
  nwalkers: 48
  nsteps: 8000
  nburn: 3000
  fit_ld1: false

combine:
  bin_widths_nm: [10, 20, 50]
  bad_wavelengths: []   # microns to mask from the combined spectrum
"""


def bootstrap(
    planet: str,
    program: str,
    outdir: Optional[Path] = None,
) -> Path:
    """Create a project directory for `planet` with a populated target.json.

    Parameters
    ----------
    planet : str
        Full canonical planet name, e.g. "WASP-69 b".
    program : str
        JWST program id, e.g. "5924" or "GO-5924".
    outdir : Path, optional
        Project directory path. Defaults to `./<planet_with_no_spaces>/` in the CWD.

    Returns
    -------
    Path
        Absolute path to the created project directory.
    """
    if outdir is None:
        safe_name = planet.replace(" ", "")
        outdir = Path.cwd() / safe_name
    outdir = Path(outdir).resolve()

    logger.info(f"Bootstrapping project for {planet} (program {program}) at {outdir}")

    logger.info("Querying NASA Exoplanet Archive...")
    target = query_target(planet, program=program)

    outdir.mkdir(parents=True, exist_ok=True)
    for sub in _PROJECT_SUBDIRS:
        (outdir / sub).mkdir(parents=True, exist_ok=True)

    target_path = outdir / "target.json"
    target.to_json(target_path)
    logger.info(f"Wrote {target_path}")

    config_path = outdir / "config.yaml"
    if not config_path.exists():
        # Fill machine paths from the environment when available so a fresh
        # checkout doesn't inherit someone else's hardcoded directories.
        ld_data = os.environ.get("EXOTIC_LD_DATA") or "CHANGE_ME-path-to-exotic_ld_data"
        crds_cache = os.environ.get("CRDS_PATH") or "~/crds_cache/"
        config_path.write_text(_CONFIG_TEMPLATE.format(
            planet_name=planet, ld_data=ld_data, crds_cache=crds_cache))
        logger.info(f"Wrote {config_path}")
        if ld_data.startswith("CHANGE_ME"):
            logger.warning(
                "Set paths.ld_data in %s to your exotic_ld data dir "
                "(or export EXOTIC_LD_DATA) before running spectral fits.",
                config_path,
            )
    else:
        logger.info(f"Kept existing {config_path}")

    readme_path = outdir / "README.md"
    if not readme_path.exists():
        readme_path.write_text(textwrap.dedent(f"""\
            # {planet}

            Auto-generated by `tswift.bootstrap("{planet}", program="{program}")`.

            Next steps:

            ```python
            from tswift import fetch
            # narrow with target_name=... and instrument=... once you see the obs list
            fetch("{outdir.name}", program_id="{program}")
            ```

            - `target.json` holds system parameters from NASA Exoplanet Archive.
            - `config.yaml` holds pipeline knobs (edit these, not target.json).
            - `data/uncal/` will hold raw MAST downloads after `fetch()`.
        """))

    return outdir


def load_target(project_dir: Path) -> Target:
    """Load `target.json` from a bootstrapped project directory."""
    return Target.from_json(Path(project_dir) / "target.json")
